src/Entity/FonctionValide.php
<?php

namespace App\Entity;

use App\Repository\FonctionValideRepository;
use Doctrine\ORM\Mapping as ORM;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: FonctionValideRepository::class)]
#[ORM\HasLifecycleCallbacks]

#[UniqueEntity(
    fields: ['annee', 'nummois'],
    message: 'Ce libellé existent déjà.'
)]
class FonctionValide
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column]
    private ?string $annee = null;


    #[ORM\Column]
    private ?string $nummois = null;

    #[ORM\Column]
    private ?string $ensemble = null;

    #[ORM\Column]
    private ?string $prod_alim_bois_nalc = null;

    #[ORM\Column]
    private ?string $tissu_vetement = null;

    #[ORM\Column]
    private ?string $logt_et_combust = null;

    #[ORM\Column]
    private ?string $am_eqmena_entc_m = null;

    #[ORM\Column]
    private ?string $sante = null;

    #[ORM\Column]
    private ?string $transports = null;

    #[ORM\Column]
    private ?string $loisir_spect_cult = null;

    #[ORM\Column]
    private ?string $enseignement = null;

    #[ORM\Column]
    private ?string $hotel_cafe_rest = null;

    #[ORM\Column]
    private ?string $autres_bien_serv = null;

    #[ORM\Column]
    private ?string $bois_alc_tab = null;

    #[ORM\Column]
    private ?string $communications = null;

    #[ORM\Column(type: 'string', length: 10, nullable: true)]
    private ?string $deletedAt = null;


    public function getDeletedAt(): ?string
    {
        return $this->deletedAt;
    }

    public function setDeletedAt(?string $deletedAt): self
    {
        $this->deletedAt = $deletedAt;
        return $this;
    }

    #[ORM\Column(type: 'string', length: 19)]
    private ?string $createdAt = null;


    #[ORM\Column(type: 'string', length: 19, nullable: true)]
    private ?string $updatedAt = null;

    #[ORM\OneToMany(mappedBy: 'fonctionValide', targetEntity: FonctionValideHistorique::class, cascade: ['persist', 'remove'])]
    private Collection $historiques;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $createdBy = null;

    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?string $createdBy): self
    {
        $this->createdBy = $createdBy;
        return $this;
    }

    public function __construct()
    {
        $this->createdAt = (new \DateTimeImmutable('now', new \DateTimeZone('Indian/Antananarivo')))->format('Y-m-d H:i:s');
        $this->historiques = new ArrayCollection();
    }


    public function getHistoriques(): Collection
    {
        return $this->historiques;
    }

    public function addHistorique(FonctionValideHistorique $historique): self
    {
        if (!$this->historiques->contains($historique)) {
            $this->historiques[] = $historique;
            $historique->setFonctionValide($this);
        }

        return $this;
    }


    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updatedAt = (new \DateTimeImmutable('now', new \DateTimeZone('Indian/Antananarivo')))->format('Y-m-d H:i:s');
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        if ($this->createdAt === null) {
            return null;
        }
        if ($this->createdAt instanceof \DateTimeImmutable) {
            return $this->createdAt;
        }

        // Si c'est une string, la convertir en DateTimeImmutable
        return \DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $this->createdAt);
    }

    public function setCreatedAt(String $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
{
    if ($this->updatedAt === null) {
        return null;
    }
    if ($this->updatedAt instanceof \DateTimeImmutable) {
        return $this->updatedAt;
    }

    return \DateTimeImmutable::createFromFormat('Y-m-d H:i:s', $this->updatedAt);
    }

    public function setUpdatedAt(?string $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    public function isDeleted(): bool
    {
        return $this->deletedAt !== null;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnnee(): ?string
    {
        return $this->annee;
    }

    public function setAnnee(string $annee): static
    {
        $this->annee = $annee;

        return $this;
    }

    public function getNummois(): ?string
    {
        return $this->nummois;
    }

    public function setNummois(string $nummois): static
    {
        $this->nummois = $nummois;

        return $this;
    }

    public function getEnsemble(): ?string
    {
        return $this->ensemble;
    }

    public function setEnsemble(string $ensemble): static
    {
        $this->ensemble = $ensemble;

        return $this;
    }

    public function getProdAlimBoisNalc(): ?string
    {
        return $this->prod_alim_bois_nalc;
    }

    public function setProdAlimBoisNalc(string $prod_alim_bois_nalc): static
    {
        $this->prod_alim_bois_nalc = $prod_alim_bois_nalc;

        return $this;
    }

    public function getTissuVetement(): ?string
    {
        return $this->tissu_vetement;
    }

    public function setTissuVetement(string $tissu_vetement): static
    {
        $this->tissu_vetement = $tissu_vetement;

        return $this;
    }

    public function getLogtEtCombust(): ?string
    {
        return $this->logt_et_combust;
    }

    public function setLogtEtCombust(string $logt_et_combust): static
    {
        $this->logt_et_combust = $logt_et_combust;

        return $this;
    }

    public function getAmEqmenaEntcM(): ?string
    {
        return $this->am_eqmena_entc_m;
    }

    public function setAmEqmenaEntcM(string $am_eqmena_entc_m): static
    {
        $this->am_eqmena_entc_m = $am_eqmena_entc_m;

        return $this;
    }

    public function getSante(): ?string
    {
        return $this->sante;
    }

    public function setSante(string $sante): static
    {
        $this->sante = $sante;

        return $this;
    }

    public function getTransports(): ?string
    {
        return $this->transports;
    }

    public function setTransports(string $transports): static
    {
        $this->transports = $transports;

        return $this;
    }

    public function getLoisirSpectCult(): ?string
    {
        return $this->loisir_spect_cult;
    }

    public function setLoisirSpectCult(string $loisir_spect_cult): static
    {
        $this->loisir_spect_cult = $loisir_spect_cult;

        return $this;
    }

    public function getEnseignement(): ?string
    {
        return $this->enseignement;
    }

    public function setEnseignement(string $enseignement): static
    {
        $this->enseignement = $enseignement;

        return $this;
    }

    public function getHotelCafeRest(): ?string
    {
        return $this->hotel_cafe_rest;
    }

    public function setHotelCafeRest(string $hotel_cafe_rest): static
    {
        $this->hotel_cafe_rest = $hotel_cafe_rest;

        return $this;
    }

    public function getAutresBienServ(): ?string
    {
        return $this->autres_bien_serv;
    }

    public function setAutresBienServ(string $autres_bien_serv): static
    {
        $this->autres_bien_serv = $autres_bien_serv;

        return $this;
    }

    public function getBoisAlcTab(): ?string
    {
        return $this->bois_alc_tab;
    }

    public function setBoisAlcTab(string $bois_alc_tab): static
    {
        $this->bois_alc_tab = $bois_alc_tab;

        return $this;
    }

    public function getCommunications(): ?string
    {
        return $this->communications;
    }

    public function setCommunications(string $communications): static
    {
        $this->communications = $communications;

        return $this;
    }
}

src/Form/FonctionValideType.php
<?php

namespace App\Form;

use App\Entity\FonctionValide;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


class FonctionValideType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $anneeField = function (string $label) {
            return [
                'label' => $label,
                    'attr' => [
                        'min' => 1900,
                        'max' => 2100,
                        'step' => 1,
                        'class' => 'numeric-field'
                    ],
                    'constraints' => [
                        new Assert\NotBlank(),
                        new Assert\Range([
                            'min' => 1900,
                            'max' => 2100,
                            'notInRangeMessage' => 'L\'année doit être comprise entre {{ min }} et {{ max }}.'
                        ]),
                        new Assert\Type(['type' => 'integer'])
                    ]
            ];
        };

        $moisField = function (string $label) {
            return [
                'label' => $label,
                'choices' => [
                    'Janvier' => 1,
                    'Février' => 2,
                    'Mars' => 3,
                    'Avril' => 4,
                    'Mai' => 5,
                    'Juin' => 6,
                    'Juillet' => 7,
                    'Août' => 8,
                    'Septembre' => 9,
                    'Octobre' => 10,
                    'Novembre' => 11,
                    'Décembre' => 12,
                ],
                'placeholder' => 'Sélectionnez un mois',
                'attr' => [
                    'class' => 'form-select'
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                ]
            ];
        };

        $numberField = function (string $label) {
            return [
                'label' => $label,
                'scale' => 2,
                'html5' => true,
                'attr' => [
                    'step' => '0.01',
                    'min' => 0,
                    'class' => 'numeric-field'
                ],
                'constraints' => [
                    new Assert\NotBlank(),
                    new Assert\Type(['type' => 'numeric'])
                ]
            ];
        };

        $builder
            ->add('annee', IntegerType::class, $anneeField('Année'))
            ->add('nummois', ChoiceType::class, $moisField('Numéro du mois'))

            ->add('ensemble', NumberType::class, $numberField('Ensemble'))
            ->add('prod_alim_bois_nalc', NumberType::class, $numberField('Produits alimentaires et boissons non alcoolisées'))
            ->add('tissu_vetement', NumberType::class, $numberField('Tissus et vêtements'))
            ->add('logt_et_combust', NumberType::class, $numberField('Logement et combustibles'))
            ->add('am_eqmena_entc_m', NumberType::class, $numberField('Ameublement, équipement ménager et entretien cour maison'))
            ->add('sante', NumberType::class, $numberField('Santé'))
            ->add('transports', NumberType::class, $numberField('Transports'))
            ->add('loisir_spect_cult', NumberType::class, $numberField('Loisirs et culture'))
            ->add('enseignement', NumberType::class, $numberField('Enseignement, education'))
            ->add('hotel_cafe_rest', NumberType::class, $numberField('Hôtelierie, cafés et restaurants'))
            ->add('autres_bien_serv', NumberType::class, $numberField('Autres biens et services'))
            ->add('bois_alc_tab', NumberType::class, $numberField('Boissons alcoolisées et tabac'))
            ->add('communications', NumberType::class, $numberField('Communications'));
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FonctionValide::class,
        ]);
    }

}

src/Controller/FonctionValideController.php
<?php

namespace App\Controller;

use App\Entity\FonctionValide;
use App\Form\FonctionValideType;
use App\Repository\FonctionValideRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use App\Entity\FonctionValideHistorique;

#[Route('/fonction/valide')]
final class FonctionValideController extends AbstractController
{
    #[Route(name: 'app_fonction_valide_index', methods: ['GET'])]
    public function index(FonctionValideRepository $fonctionValideRepository): Response
{
    return $this->render('fonction_valide/index.html.twig', [
        'fonction_valides' => $fonctionValideRepository->findAllNonDeleted(),
    ]);
}

    #[Route('/new', name: 'app_fonction_valide_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $fonctionValide = new FonctionValide();
        $form = $this->createForm(FonctionValideType::class, $fonctionValide);
        $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $fonctionValide->setCreatedBy($this->getUser()->getNom()); // Stocke le créateur
        $entityManager->persist($fonctionValide);
        $entityManager->flush();

        return $this->redirectToRoute('app_fonction_valide_index');
    }
        return $this->render('fonction_valide/new.html.twig', [
            'fonction_valide' => $fonctionValide,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fonction_valide_show', methods: ['GET'])]
    public function show(FonctionValide $fonctionValide): Response
    {
        return $this->render('fonction_valide/show.html.twig', [
            'fonction_valide' => $fonctionValide,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_fonction_valide_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FonctionValide $fonctionValide, EntityManagerInterface $entityManager): Response
       {
        $form = $this->createForm(FonctionValideType::class, $fonctionValide);
        $form->handleRequest($request);

       if ($form->isSubmitted() && $form->isValid()) {
        // Crée une nouvelle ligne d'historique
        $historique = new FonctionValideHistorique();
        $historique->setModifiePar($this->getUser()->getNom());
        $fonctionValide->addHistorique($historique);

        $entityManager->flush();

        return $this->redirectToRoute('app_fonction_valide_index');
        }

        return $this->render('fonction_valide/edit.html.twig', [
            'form' => $form,
            'fonction_valide' => $fonctionValide,
        ]);
        }

    #[Route('/{id}', name: 'app_fonction_valide_delete', methods: ['POST'])]
    public function delete(Request $request, FonctionValide $fonctionValide, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fonctionValide->getId(), $request->request->get('_token'))) {
            // Stocker la date actuelle au format string, ex: '2025-08-11'
            $now = new \DateTimeImmutable('now', new \DateTimeZone('Indian/Antananarivo'));
            $fonctionValide->setDeletedAt($now->format('Y-m-d'));
            
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_fonction_valide_index');
    }

}

templates/fonction_valide/_form.html.twig
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
{% endblock %}

{% block body %}
<div class="custom-container">

    <div class="custom-card">
        <div class="custom-card-body">
            <h4>{{ button_title|default("Ajouter l'evolution d'indice fonction") }}</h4>
            {{ form_start(form, {'attr': {'class': 'custom-form'}}) }}
            
            {# ✅ Affiche les erreurs globales ici #}
            {% if form.vars.errors|length > 0 %}
                <div class="form-global-errors">
                    {{ form_errors(form) }}
                </div>
            {% endif %}

            <div class="form-grid">
                {% for field in form %}
                    {% if field.vars.name != '_token' %}
                        <div class="form-group">
                            {{ form_label(field, null, {'label_attr': {'class': 'custom-label'}}) }}
                            {{ form_widget(field, {'attr': {'class': 'custom-input'}}) }}
                            {{ form_errors(field) }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <div class="form-actions">
                <button type="submit" class="btn-primary">
                    {{ button_label|default('Ajouter') }}
                </button>
                <a href="{{ path('app_fonction_valide_index') }}" class="btn-secondary">
                    Annuler
                </a>
            </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

templates/fonction_valide/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FonctionValide{% endblock %}

{% block body %}
<div>
    <h1>Modifier</h1>

    {{ include('fonction_valide/_form.html.twig', {'button_label': 'Modifier', 'button_title' :"Modifier l'evolution d'indice fonction"}) }}
</div>
  
{% endblock %}

templates/fonction_valide/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FonctionValide index{% endblock %}



{% block body %}
    <div class="entete">

<style>
    .entete{ 
    padding: 20px;
    margin-left: 15%; 
    padding-bottom: 0;
}
.add{
    background-color: #2c5eaa;
    color: white;
    padding: 10px 20px;
    border-radius: 5px;
    text-decoration: none;
    font-size: 14px;
    text-decoration: none;
    height: 40px;
    margin-left: 13px;
}
.heading {
    display: flex;
    background-color: #232f3e;
    box-shadow: 0px 1px 2px #232f3e;

}
h1 {
    color: coral;
    font-weight: bold; 
    background: transparent;
    padding: 7px;
    
}
.outer-wrapper {
    margin-bottom: 50px;
    margin-left: 17%;
    margin-right: 10px;
    border-radius: 4px;
    box-shadow: 0px 0px 3px #9e9d9d;
    width: 80vw !important;
    justify-content: center;  /* Centrage horizontal */
    align-items: center;      /* Centrage vertical */
    
}
.table-wrapper {
    overflow-y: scroll;
    overflow-x: scroll;
    height: fit-content;
    margin: 15px;
    padding-bottom: 20px;    
}

table {   
    min-width: max-content;    
    border-collapse: separate;
    border-spacing: 0px;  
    font-size: 13px;
    text-align: center;
}


table th{
    position: sticky; 
    top: 0px;  
    background-color: #cbced1;
    color: rgb(12, 12, 11);  
    text-align: center;
    font-weight: normal;
} 
table th, table td {   
    padding: 15px;
    padding-top: 10px;
    padding-bottom: 10px;
    
}
table td {
    text-align: center; 
    padding-left: 20px;
    
}


/* Appliquer une bordure de 5px au tooltip Bootstrap */
.tooltip .tooltip-inner {
    border: 5px solid #2e4ead; /* couleur au choix */
    background-color: #fff;
    color: #333;
    font-size: 14px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
    width: 300px;
}

.modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0,0,0,0.6);
    display: none;
    justify-content: center;
    align-items: center;
    z-index: 1000;
}

.modal-content {
    background: white;
    padding: 0px ;
    border-radius: 8px;
    width: 400px;
    max-width: 90%;
    box-shadow: 0 0 10px rgba(0,0,0,0.3);
    position: relative;
    left:30%;
    animation: animatetop 0.3s;
    top: 25%;
}

.close-button {
    position: absolute;
    top: 8px;
    right: 12px;
    font-size: 20px;
    cursor: pointer;

}
.btn-add {
    display: flex;
    flex: nowrap;
    gap: 5px;
}
#modalDetails {
    margin-top: 20px;
    margin-left: 10px
}
/* Add Animation */
@-webkit-keyframes animatetop {
  from {top:-300px; opacity:0} 
  to {top:0; opacity:1}
}

@keyframes animatetop {
  from {top:-300px; opacity:0}
  to {top:0; opacity:1}
}

.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}

.modal-header {
 text-align: center;
    padding: 10px;
    background-color: #f1f1f1;
    border-bottom: 1px solid #ddd;
  background-color: #5cb85c;
  color: white;
}

#refreshTable {
    transition: transform 0.3s ease;
}
#refreshTable:active {
    transform: rotate(180deg);
}

@media (max-width: 850px) {
    .entete {
        margin-left: 0;
        margin-top: 20px;
    }
}
    </style>
    
        <div class="row my-4 px-3 align-items-center justify-content-between">
            <div class="col-md-3">
                <label for="columnSelect" class="form-label mb-1">Choisir une colonne :</label>
                <select id="columnSelect" class="form-select">
                    <option value="">-- Sélectionner --</option>
                    <option value="0">Annee</option>
                    <option value="1">Nummois</option>
                    <option value="2">Ensemble</option>
                    <option value="3">Prod_alim_bois_nalc</option>
                    <option value="4">Tissu_vetement</option>
                    <option value="5">Logt_et_combust</option>
                    <option value="6">Am_eqmena_entc_m</option>
                    <option value="7">Sante</option>
                    <option value="8">Transports</option>
                    <option value="9">Loisir_spect_cult</option>
                    <option value="10">Enseignement</option>
                    <option value="11">Hotel_cafe_rest</option>
                    <option value="12">Autres_bien_serv</option>
                    <option value="13">Bois_alc_tab</option>
                    <option value="14">Communications</option>
                </select>
            </div>

            <div class="col-md-3 d-none" id="searchColumnWrapper">
                <label for="searchInput" class="form-label mb-1">Rechercher :</label>
                <input type="text" id="searchInput" class="form-control" placeholder="Entrez une valeur...">
            </div>

            <div class="col-md-2 text-end d-flex justify-content-end gap-2">
                <a class="btn btn-outline-secondary" id="refreshTable" title="Rafraîchir">
                    <i class="bi bi-arrow-clockwise"></i>
                </a>
                <a class="add btn btn-primary btn-add" href="{{ path('app_fonction_valide_new') }}">
                    <i class="bi bi-plus-circle"></i> Ajouter
                </a>
            </div>
        </div>
    </div>

    <div class="outer-wrapper">
        <div class="table-wrapper">
            <table class="table  table-hover" id="sortableTable">
                <thead class="table-secondary">
                    <tr>
                        <th>ANNEE</th>
                        <th>NUMMOIS</th>
                        <th>ENSEMBLE</th>
                        <th>PROD_ALIM_BOIS_NALC</th>
                        <th>TISSU_VETEMENT</th>
                        <th>LOGT_ET_COMBUST</th>
                        <th>AM_EQMENA_ENTC_M</th>
                        <th>SANTE</th>
                        <th>TRANSPORTS</th>
                        <th>LOISIR_SPECT_CULT</th>
                        <th>ENSEIGNEMENT</th>
                        <th>HOTEL_CAFE_REST</th>
                        <th>AUTRES_BIEN_SERV</th>
                        <th>BOIS_ALC_TAB</th>
                        <th>COMMUNICATIONS</th>
                        <th>ACTIONS</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fonction_valide in fonction_valides |sort((a, b) => b.createdAt <=> a.createdAt)  %}
                        {% set dernier_historique = fonction_valide.historiques|last %}
                        <tr 
                            data-matricule="{{ app.user.matricule }}"
                            data-created="{{ fonction_valide.createdAt ? fonction_valide.createdAt|date('d/m/Y H:i') : 'N/A' }}"
                            data-createdby="{{ fonction_valide.createdBy ?? 'N/A' }}"
                            data-updated="{{ fonction_valide.updatedAt ? fonction_valide.updatedAt|date('d/m/Y H:i') : 'N/A' }}"
                            data-updatedby="{{ dernier_historique.modifiePar ?? 'N/A' }}"
                        >
                            <td class="modal-trigger">{{ fonction_valide.annee }}</td>
                            <td class="modal-trigger">{{ fonction_valide.nummois }}</td>
                            <td class="modal-trigger">{{ fonction_valide.ensemble }}</td>
                            <td class="modal-trigger">{{ fonction_valide.prodAlimBoisNalc }}</td>
                            <td class="modal-trigger">{{ fonction_valide.tissuVetement }}</td>
                            <td class="modal-trigger">{{ fonction_valide.logtEtCombust }}</td>
                            <td class="modal-trigger">{{ fonction_valide.amEqmenaEntcM }}</td>
                            <td class="modal-trigger">{{ fonction_valide.sante }}</td>
                            <td class="modal-trigger">{{ fonction_valide.transports }}</td>
                            <td class="modal-trigger">{{ fonction_valide.loisirSpectCult }}</td>
                            <td class="modal-trigger">{{ fonction_valide.enseignement }}</td>
                            <td class="modal-trigger">{{ fonction_valide.hotelCafeRest }}</td>
                            <td class="modal-trigger">{{ fonction_valide.autresBienServ }}</td>
                            <td class="modal-trigger">{{ fonction_valide.boisAlcTab }}</td>
                            <td class="modal-trigger">{{ fonction_valide.communications }}</td>
                            <td>
                                <a href="{{ path('app_fonction_valide_show', {'id': fonction_valide.id}) }}"
                                    class="btn btn-sm btn-outline-success" title="Voir">
                                    <i class="bi bi-eye-fill"></i>
                                </a>
                                <a href="{{ path('app_fonction_valide_edit', {'id': fonction_valide.id}) }}"
                                    class="btn btn-sm btn-outline-primary" title="Modifier">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <form method="post"
                                    action="{{ path('app_fonction_valide_delete', {'id': fonction_valide.id}) }}"
                                    class="form-delete"
                                    data-id="{{ fonction_valide.id }}"
                                    style="display:inline;">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fonction_valide.id) }}">
                                    {#<button type="submit" class="btn btn-sm btn-danger">
                                        <i class="bi bi-trash"></i>
                                    </button>#}
                                </form>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="16">Liste vide</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal personnalisé -->
    <div id="customModal" class="modal-overlay">
        <div class="modal-content">
            <div class="modal-header">
                <span class="close-button" id="closeModal">&times;</span>
                <h5>Détails de l'enregistrement</h5>       
            </div>
            <div id="modalDetails">
                <!-- Contenu injecté dynamiquement -->
            </div>
        </div>
    </div>

    <div id="pagination-wrapper"></div>
    <script src="{{ asset('js/fonctions_valide.js') }}"></script>
        {% block javascripts %}
        <script>
        document.addEventListener("DOMContentLoaded", function () {
            const refreshBtn = document.getElementById("refreshTable");

            refreshBtn.addEventListener("click", function () {
                refreshBtn.classList.add("spin"); // Pour animation si tu veux
                location.reload();
            });
        });
        </script>
        {% endblock %}
{% endblock %}

templates/fonction_valide/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}nouveau{% endblock %}

{% block body %}
   
<div>
    {{ include('fonction_valide/_form.html.twig') }}

</div>

{% endblock %}